#!/usr/bin/env python3
import sys
from datetime import datetime

def preposessing(ln_min, la_min, ln_max, la_max, time_min, time_max, fin, fout):
    """Filtering out all records outside the bounding box: 
       [(ln_min, la_min), (ln_max, la_max)]
    """
    assert(ln_min < ln_max)
    assert(la_min < la_max)
    assert(isinstance(time_min, datetime))
    assert(isinstance(time_max, datetime))
    assert(time_min < time_max)
    
    # 1    * Photo/video identifier 
    # 2    * User ID
    # 4    * Timestamp
    # 11   * Longitude
    # 12   * Latitude
    # 13   * Accuracy
    # 14   * Photo/video page URL
    # 23   * Photos/video provider (0 = photo, 1 = video)

    with open(fout, 'w') as fo:
        #fo.write('Photo_ID, User_ID, Timestamp, Longitude, Latitude, Accuracy, URL, Marker(photo=0 video=1)\n')
        with open(fin, 'r') as fi:
            for line in fi:
                t = line.strip().split('\t')
                pid    = t[0].strip()
                uid    = t[1].strip()
                time   = t[3].strip()
                lng    = t[10].strip()
                lat    = t[11].strip()
                acc    = t[12].strip()
                url    = t[13].strip()
                marker = t[22].strip()
                
                if len(pid) == 0 or len(uid) == 0 or \
                   len(time) == 0 or len(ln) == 0 or \
                   len(la) == 0 or len(acc) == 0 or \
                   len(url) == 0 or len(marker) == 0: continue

                ln = float(ln)
                la = float(la)
                if ln < ln_min or lng > ln_max: continue
                if la< la_min or la > la_max: continue

                dt = datetime.strptime(time, '%Y-%m-%d %H:%M:%S.%f')
                if dt < time_min or dt > time_max: continue

                fo.write(pid + ',' + uid + ',' + time + ',' + \
                         str(ln) + ',' + str(la) + ',' + \
                         acc + ',' + url + ',' + marker + '\n')


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print('Usage:', sys.argv[0], 'YFCC100M')
        sys.exit(0)

    fin = sys.argv[1]
    fout = './out.' + fin.split('/')[-1]
    ln_min = 141.9
    ln_max = 147.1
    la_min = -39.3 
    la_max = -35.8 
    time_min = datetime.strptime('2000-12-24 00:00:00', '%Y-%m-%d %H:%M:%S')
    time_max = datetime.strptime('2010-12-24 23:59:59', '%Y-%m-%d %H:%M:%S')
    
    preposessing(ln_min, la_min, ln_max, la_max, time_min, time_max, fin, fout)
